// Cached CrossReferenceSource text is generated by InDesign's panel encoder.
// Translation, normalizers and the workbook importer may not rewrite it.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {normalizeContentId} from './ContentIds.mjs';
import {isStrictlyInside} from './PathSafety.mjs';

export function panelManagedContent(text){
  const values=new Map();
  const starts=[...text.matchAll(/<CrossReferenceSource\b[^>]*>/gu)].filter(match=>!match[0].endsWith('/>'));
  const blocks=[...text.matchAll(/<CrossReferenceSource\b[^>]*>([\s\S]*?)<\/CrossReferenceSource>/gu)];
  if(starts.length!==blocks.length)throw Error('Unbalanced CrossReferenceSource elements.');
  for(const block of blocks){
    if(/<CrossReferenceSource\b/u.test(block[1]))throw Error('Nested CrossReferenceSource elements.');
    const contents=[...block[1].matchAll(/<Content\b([^>]*?)(?:\/>|>([\s\S]*?)<\/Content>)/gu)];
    if(!contents.length)throw Error('Cross-reference has no indexed Content elements.');
    for(const content of contents){
      const raw=/\bid\s*=\s*"([^"]+)"/u.exec(content[1])?.[1];
      const id=normalizeContentId(raw);
      if(!id || values.has(id))throw Error('Missing or duplicate panel-managed Content ID.');
      values.set(id,String(content[2]||'').replace(/\r\n/gu,'\n'));
    }
  }
  return values;
}
export function loadPanelManagedContent(config,manifest){
  const files=manifest.icmlFiles || [],result=new Map();
  if(files.length>5000)throw Error('Panel-managed ICML inventory exceeds limit.');
  const prior=manifest.import?.icmlFiles || manifest.invalidatedImport?.import?.icmlFiles;
  const textRoot=config.productionWorkspace?.textFolder || (manifest.document?.path && path.extname(manifest.document.path).toLowerCase()==='.indd' ? path.dirname(manifest.document.path) : null);
  const expected=new Map((prior || files).map(file=>[path.resolve(file.path).toLowerCase(),String(file.afterSha256 || file.sha256 || '').toUpperCase()]));
  const seen=new Set();
  for(const file of files){
    const full=path.resolve(file.path),key=full.toLowerCase();
    if(!textRoot || !isStrictlyInside(full,textRoot) || path.extname(full).toLowerCase()!=='.icml' || seen.has(key))throw Error('Invalid panel-managed ICML path.');
    seen.add(key);
    const text=fs.readFileSync(full,'utf8').replace(/^\uFEFF/u,'');
    const hash=crypto.createHash('sha256').update(text).digest('hex').toUpperCase();
    if(hash!==expected.get(key))throw Error('ICML changed since the last accepted export/import; panel cache cannot be inferred.');
    for(const [id,value] of panelManagedContent(text)){
      if(result.has(id))throw Error('Duplicate panel-managed Content ID across ICML files.');
      result.set(id,value);
    }
  }
  return result;
}
export function preservePanelManagedContent(rows,values){
  const found=new Set();let restored=0;
  for(let r=1;r<rows.length;r++){
    const id=normalizeContentId(rows[r][2]);
    if(!values.has(id))continue;
    if(found.has(id))throw Error('Duplicate panel-managed workbook Content ID.');
    found.add(id);if(rows[r][3]!==values.get(id))restored++;
    rows[r][3]=values.get(id);
  }
  if(found.size!==values.size)throw Error('Workbook is missing panel-managed Content IDs.');
  return {method:'cross_reference_panel_encoder_only',segments:found.size,discardedModelEdits:restored};
}
